#ifndef __uidefs_h__
#define __uidefs_h__


// screen
#define SCREEN_WIDTH 800 //1366
#define SCREEN_HEIGHT 700 //768

// game area
#define GAME_AREA_WIDTH 300
#define GAME_AREA_HEIGHT 600
#define GAME_AREA_X (SCREEN_WIDTH / 2 - GAME_AREA_WIDTH / 2)
#define GAME_AREA_Y (SCREEN_HEIGHT / 2 - GAME_AREA_HEIGHT / 2)

#define GAME_AREA_SQUARE_SIZE 30

#define GAME_AREA_COLOR_R 20
#define GAME_AREA_COLOR_G 20
#define GAME_AREA_COLOR_B 32

// background
#define BACKGROUND_COLOR_R 6
#define BACKGROUND_COLOR_G 6
#define BACKGROUND_COLOR_B 14

// score text
#define SCORE_COLOR_R 160
#define SCORE_COLOR_G 160
#define SCORE_COLOR_B 14

#define SCORE_AREA_WIDTH 160
#define SCORE_AREA_HEIGHT 40
#define SCORE_AREA_X (GAME_AREA_X - SCORE_AREA_WIDTH - 40)
#define SCORE_AREA_Y (GAME_AREA_Y + GAME_AREA_HEIGHT - SCORE_AREA_HEIGHT)

#define SCORE_LABEL_AREA_WIDTH 160
#define SCORE_LABEL_AREA_HEIGHT 12
#define SCORE_LABEL_AREA_X SCORE_AREA_X
#define SCORE_LABEL_AREA_Y (SCORE_AREA_Y - 12)

#define TIME_AREA_WIDTH 160
#define TIME_AREA_HEIGHT 40
#define TIME_AREA_X (GAME_AREA_X - TIME_AREA_WIDTH - 40)
#define TIME_AREA_Y (SCORE_AREA_Y - TIME_AREA_HEIGHT - 30)

#define TIME_LABEL_AREA_WIDTH 160
#define TIME_LABEL_AREA_HEIGHT 12
#define TIME_LABEL_AREA_X TIME_AREA_X
#define TIME_LABEL_AREA_Y (TIME_AREA_Y - 12)

#define LINES_AREA_WIDTH 160
#define LINES_AREA_HEIGHT 40
#define LINES_AREA_X (GAME_AREA_X - LEVEL_AREA_WIDTH - 40)
#define LINES_AREA_Y (TIME_AREA_Y - LEVEL_AREA_HEIGHT - 30)

#define LINES_LABEL_AREA_WIDTH 160
#define LINES_LABEL_AREA_HEIGHT 12
#define LINES_LABEL_AREA_X LINES_AREA_X
#define LINES_LABEL_AREA_Y (LINES_AREA_Y - 12)

#define LEVEL_AREA_WIDTH 160
#define LEVEL_AREA_HEIGHT 40
#define LEVEL_AREA_X (GAME_AREA_X - LEVEL_AREA_WIDTH - 40)
#define LEVEL_AREA_Y (LINES_AREA_Y - LEVEL_AREA_HEIGHT - 30)

#define LEVEL_LABEL_AREA_WIDTH 160
#define LEVEL_LABEL_AREA_HEIGHT 12
#define LEVEL_LABEL_AREA_X LEVEL_AREA_X
#define LEVEL_LABEL_AREA_Y (LEVEL_AREA_Y - 12)

#define NEXT_LABEL_WIDTH 160
#define NEXT_LABEL_HEIGHT 12
#define NEXT_LABEL_X (GAME_AREA_X + GAME_AREA_WIDTH + 70)
#define NEXT_LABEL_Y GAME_AREA_Y

#define NEXT_WIDTH (GAME_AREA_SQUARE_SIZE * 4)
#define NEXT_HEIGHT (GAME_AREA_SQUARE_SIZE * 2)
#define NEXT_X (GAME_AREA_X + GAME_AREA_WIDTH + 70)
#define NEXT_Y (NEXT_LABEL_Y + 30)

#define HIGH_SCORE_LABEL_AREA_WIDTH 160
#define HIGH_SCORE_LABEL_AREA_HEIGHT 16
#define HIGH_SCORE_LABEL_AREA_X NEXT_LABEL_X
#define HIGH_SCORE_LABEL_AREA_Y (NEXT_Y + NEXT_HEIGHT + 24)

#define HIGH_SCORE_AREA_WIDTH 160
#define HIGH_SCORE_AREA_HEIGHT 40
#define HIGH_SCORE_AREA_X (GAME_AREA_X + GAME_AREA_WIDTH + 70)
#define HIGH_SCORE_AREA_Y (HIGH_SCORE_LABEL_AREA_Y + 16)

#define HIGH_SCORE_NEXT_AREA_WIDTH 180
#define HIGH_SCORE_NEXT_AREA_HEIGHT 40
#define HIGH_SCORE_NEXT_AREA_X (GAME_AREA_X + GAME_AREA_WIDTH + 70)
#define HIGH_SCORE_NEXT_AREA_Y (HIGH_SCORE_AREA_Y + HIGH_SCORE_AREA_HEIGHT + 30)

#define HIGH_SCORE_NEXT_LABEL_AREA_WIDTH HIGH_SCORE_NEXT_AREA_WIDTH
#define HIGH_SCORE_NEXT_LABEL_AREA_HEIGHT 16
#define HIGH_SCORE_NEXT_LABEL_AREA_X HIGH_SCORE_NEXT_AREA_X
#define HIGH_SCORE_NEXT_LABEL_AREA_Y (HIGH_SCORE_NEXT_AREA_Y - 16)


#endif // __uidefs_h__

